const affixRoots = {
  kain: {
    label: "kain", gloss: "eat", description: "The root for eating branches into actor, object, location, and beneficiary-oriented forms.",
    paths: [
      { affix: "-um-", form: "kumain", meaning: "to eat; completed actor-focused action", focus: "Actor", pattern: "k + um + ain", sentence: "Kumain ako ng mangga.", translation: "I ate mango." },
      { affix: "-in", form: "kinain", meaning: "ate a particular thing; completed object-focused action", focus: "Object", pattern: "k + in + ain", sentence: "Kinain ko ang mangga.", translation: "I ate the mango." },
      { affix: "-in", form: "kainin", meaning: "to eat a particular thing", focus: "Object", pattern: "kain + in", sentence: "Kainin mo ang gulay.", translation: "Eat the vegetables." },
      { affix: "-an", form: "kainan", meaning: "an eating place; a place to eat", focus: "Location", pattern: "kain + an", sentence: "May kainan sa kanto.", translation: "There is an eatery on the corner." },
      { affix: "magpa-", form: "magpakain", meaning: "to feed someone", focus: "Actor / cause", pattern: "magpa + kain", sentence: "Magpakain tayo ng mga pusa.", translation: "Let’s feed the cats." }
    ]
  },
  sulat: {
    label: "sulat", gloss: "write", description: "This root shows how the same event can highlight the writer, a written thing, or the recipient.",
    paths: [
      { affix: "-um-", form: "sumulat", meaning: "to write; completed actor-focused action", focus: "Actor", pattern: "s + um + ulat", sentence: "Sumulat si Mia ng liham.", translation: "Mia wrote a letter." },
      { affix: "mag-", form: "magsulat", meaning: "to write; intentional or habitual activity", focus: "Actor", pattern: "mag + sulat", sentence: "Magsusulat ako bukas.", translation: "I will write tomorrow." },
      { affix: "-in", form: "sulatin", meaning: "to write a specific thing", focus: "Object", pattern: "sulat + in", sentence: "Isulat mo ang pangalan mo.", translation: "Write your name." },
      { affix: "i-", form: "isulat", meaning: "to write something down", focus: "Object / theme", pattern: "i + sulat", sentence: "Isinulat niya ang sagot.", translation: "She wrote down the answer." },
      { affix: "ipag-", form: "ipagsulat", meaning: "to write for someone", focus: "Beneficiary", pattern: "ipag + sulat", sentence: "Ipagsusulat kita ng liham.", translation: "I will write you a letter." }
    ]
  },
  luto: {
    label: "luto", gloss: "cook", description: "A useful root for comparing a general cooking activity with a meal, recipient, or cooking place.",
    paths: [
      { affix: "mag-", form: "magluto", meaning: "to cook; actor-focused activity", focus: "Actor", pattern: "mag + luto", sentence: "Nagluto si Carlo ng adobo.", translation: "Carlo cooked adobo." },
      { affix: "-in", form: "lutuin", meaning: "to cook a particular thing", focus: "Object", pattern: "luto + in", sentence: "Lutuin mo ang isda.", translation: "Cook the fish." },
      { affix: "-an", form: "lutuan", meaning: "to cook for/on/at", focus: "Location", pattern: "luto + an", sentence: "Lutuan mo ako ng itlog.", translation: "Cook me an egg." },
      { affix: "ipag-", form: "ipagluto", meaning: "to cook for someone", focus: "Beneficiary", pattern: "ipag + luto", sentence: "Ipinagluto ko si Lola ng sopas.", translation: "I cooked Lola some soup." },
      { affix: "i-", form: "iluto", meaning: "to cook something for a purpose", focus: "Object / theme", pattern: "i + luto", sentence: "Iluto mo ako ng pansit.", translation: "Cook me some pancit." }
    ]
  }
};

const confusionPairs = [
  { title: "po vs. ho", summary: "Both add respect. The word before them usually decides.", rule: "Use po after most words. Ho commonly follows words ending in a vowel, especially after ikaw, oo, and certain particles; usage varies by speaker and region.", examples: [["Salamat po.", "Thank you."], ["Oho, sige.", "Yes, okay."], ["Kumusta po kayo?", "How are you? (respectful)"], ["Ikaw ho ba si Ana?", "Are you Ana? (respectful)"]] },
  { title: "hindi vs. hindi naman", summary: "Hindi simply negates. Hindi naman softens, contrasts, or reassures.", rule: "Choose hindi for a plain no or not. Add naman when the speaker means ‘not really,’ ‘not exactly,’ or is gently pushing back against an expectation.", examples: [["Hindi ako pagod.", "I am not tired."], ["Hindi naman ako pagod.", "I’m not really tired / I’m not tired, though."], ["Hindi siya nasa bahay.", "He/she is not at home."], ["Hindi naman siya galit.", "He/she is not angry, really."]] },
  { title: "ng vs. nag-", summary: "One marks a noun phrase; the other is part of an actor-focus verb.", rule: "Ng introduces a non-focused object or possessor: bumili ng tinapay. Nag- attaches to a verb root: nagluto. They may sound close, but they do completely different work.", examples: [["Bumili ako ng tinapay.", "I bought bread."], ["Nagluto ako ng tinapay.", "I baked/cooked bread."], ["Libro ng guro ito.", "This is the teacher’s book."], ["Nag-aral siya kahapon.", "He/she studied yesterday."]] },
  { title: "sa vs. nasa", summary: "Sa points to a place or direction; nasa says where something is.", rule: "Use sa for ‘to, at, in’ when adding a location phrase. Use nasa as a predicate for location, often before a specific place: Nasa bangko ang pera.", examples: [["Pupunta ako sa bangko.", "I’m going to the bank."], ["Nasa bangko ang pera.", "The money is at the bank."], ["Kumain kami sa palengke.", "We ate at the market."], ["Nasa palengke si Tita.", "Auntie is at the market."]] },
  { title: "kasi vs. dahil", summary: "Both give a reason. Kasi is conversational; dahil is more formal or emphatic.", rule: "Kasi often comes after the main point in speech. Dahil can introduce a reason more formally and is common in writing. Both are useful—match the register and rhythm of the sentence.", examples: [["Uuwi na ako kasi gabi na.", "I’m going home because it’s late."], ["Dahil gabi na, uuwi na ako.", "Because it’s late, I’m going home."], ["Pagod siya kasi nagtrabaho siya.", "He/she is tired because they worked."], ["Hindi kami lumabas dahil umulan.", "We did not go out because it rained."]] }
];

function phraseSet(core, terms, templates) {
  return [...core, ...terms.flatMap(([item, meaning]) => templates.map(([fil, en]) => [fil.replaceAll("{item}", item), en.replaceAll("{item}", meaning)]))].slice(0, 50);
}

const phrasebookScenarios = [
  { id: "basics", icon: "A", title: "First words and getting by", intro: "The courtesies, yes-and-no, and repair phrases that carry every other situation on this page.",
    phrases: phraseSet([["Opo.", "Yes."], ["Hindi po.", "No."], ["Salamat po.", "Thank you."], ["Maraming salamat po.", "Thank you very much."], ["Walang anuman po.", "You are welcome."], ["Paumanhin po.", "Excuse me."], ["Pasensya na po.", "I am sorry about that."], ["Magandang umaga po.", "Good morning."], ["Magandang gabi po.", "Good evening."], ["Paalam po.", "Goodbye."], ["Ingat po kayo.", "Take care."], ["Marunong po ba kayong mag-Ingles?", "Do you speak English?"], ["Kaunti lang po ang Tagalog ko.", "I only speak a little Tagalog."], ["Hindi ko po masyadong naiintindihan.", "I do not understand very well."], ["Puwede po bang dahan-dahan?", "Could you say that slowly?"], ["Pakiulit po.", "Please say that again."], ["Ano po ang ibig sabihin niyan?", "What does that mean?"], ["Paano po sabihin ito sa Tagalog?", "How do you say this in Tagalog?"], ["Hindi ko po alam.", "I do not know."], ["Sandali lang po.", "One moment, please."], ["Puwede po bang makahingi ng tulong?", "Could I ask for some help?"], ["Ano po ang pangalan ninyo?", "What is your name?"], ["Ako po si Sam.", "I am Sam."], ["Taga-saan po kayo?", "Where are you from?"], ["Taga-ibang bansa po ako.", "I am from another country."], ["Nakatira po ako rito.", "I live here."], ["Kumusta po kayo?", "How are you?"], ["Mabuti naman po.", "I am well."], ["Sige po.", "All right."], ["Salamat po sa pasensya ninyo.", "Thank you for your patience."]], [["banyo", "a bathroom"], ["ATM", "an ATM"], ["taxi", "a taxi"], ["tindahan", "a store"]], [["Nasaan po ang {item}?", "Where is {item}?"], ["May {item} po ba rito?", "Is there {item} here?"], ["Kailangan ko po ng {item}.", "I need {item}."], ["Malapit lang po ba ang {item}?", "Is {item} nearby?"], ["Paano po ako makakahanap ng {item}?", "How can I find {item}?"]]) },
  { id: "numbers", icon: "#", title: "Numbers, money, and time", intro: "Prices, counts, clock time, and dates — the answers you get back once you have asked the question.",
    phrases: phraseSet([["Isa, dalawa, tatlo.", "One, two, three."], ["Apat, lima, anim.", "Four, five, six."], ["Pito, walo, siyam, sampu.", "Seven, eight, nine, ten."], ["Labing-isa, labindalawa.", "Eleven, twelve."], ["Bente, trenta, kuwarenta.", "Twenty, thirty, forty."], ["Singkuwenta, sisenta, setenta.", "Fifty, sixty, seventy."], ["Otsenta, nobenta, isang daan.", "Eighty, ninety, one hundred."], ["Limang daan, isang libo.", "Five hundred, one thousand."], ["Presyo po ay sinasabi sa Espanyol na bilang.", "Prices are usually said with the Spanish-style numbers."], ["Magkano po lahat?", "How much is it altogether?"], ["Sampung piso po.", "Ten pesos."], ["Singkuwenta pesos po.", "Fifty pesos."], ["Dalawang daan po lahat.", "Two hundred in total."], ["May pambarya po ba kayo sa isang libo?", "Do you have change for a thousand?"], ["Tig-magkano po?", "How much each?"], ["Ilan po ang kailangan ninyo?", "How many do you need?"], ["Dalawa lang po.", "Just two, please."], ["Anong oras na po?", "What time is it?"], ["Alas-otso na po ng umaga.", "It is eight in the morning."], ["Alas-singko po ng hapon.", "It is five in the afternoon."], ["Alas-dose po ng tanghali.", "It is twelve noon."], ["Kalahating oras po.", "Half an hour."], ["Sampung minuto na lang po.", "Just ten more minutes."], ["Anong petsa po ngayon?", "What is the date today?"], ["Ngayong araw, bukas, kahapon.", "Today, tomorrow, yesterday."], ["Sa Lunes po.", "On Monday."], ["Sa Sabado o Linggo po.", "On Saturday or Sunday."], ["Sa susunod na linggo po.", "Next week."], ["Anong oras po kayo nagbubukas?", "What time do you open?"], ["Hanggang anong oras po kayo bukas?", "Until what time are you open?"]], [["alas-otso", "eight o’clock"], ["alas-diyes", "ten o’clock"], ["alas-tres", "three o’clock"], ["alas-sais", "six o’clock"]], [["Puwede po ba tayong magkita nang {item}?", "Could we meet at {item}?"], ["Bukas po ba kayo nang {item}?", "Are you open at {item}?"], ["Nandiyan po ako nang {item}.", "I will be there at {item}."], ["Hanggang {item} lang po ako.", "I can only stay until {item}."], ["Mga {item} po ako darating.", "I will arrive around {item}."]]) },
  { id: "replies", icon: "R", title: "Short replies and what you’ll hear", intro: "The answers you give in one breath, and the lines said back to you across a counter.",
    phrases: phraseSet([["Sige po.", "All right."], ["Oo naman po.", "Of course."], ["Opo, tama po.", "Yes, that is right."], ["Hindi po, mali po.", "No, that is wrong."], ["Ayos lang po.", "It is fine."], ["Kayo po ang bahala.", "It is up to you."], ["Puwede na po.", "That will do."], ["Tama na po.", "That is enough."], ["Sapat na po.", "That is plenty."], ["Naiintindihan ko na po.", "I understand now."], ["Hindi po ako sigurado.", "I am not sure."], ["Baka po.", "Maybe."], ["Siguro po.", "Probably."], ["Hindi ko po kaya.", "I cannot manage that."], ["Sa susunod na lang po.", "Some other time."], ["Pag-iisipan ko po muna.", "Let me think about it first."], ["Hindi po ako interesado.", "I am not interested."], ["Huwag na po, salamat.", "No thank you."], ["Naku, pasensya na po.", "Oh, I am sorry."], ["Salamat po ulit.", "Thank you again."], ["Wala pong stock.", "We are out of stock."], ["Bukas na lang po kayo.", "Please come back tomorrow."], ["Hindi po puwede.", "That is not allowed."], ["Sarado na po kami.", "We are closed already."], ["Nasa biyahe pa po.", "It is still on the way."], ["Sandali po at itatanong ko.", "One moment and I will ask."], ["Pila po kayo roon.", "Please line up over there."], ["Puno na po.", "It is full."], ["Balik po kayo mamaya.", "Come back later."], ["Ayan po, tapos na.", "There you go, it is done."]], [["ngayon", "right now"], ["mamaya", "later"], ["bukas", "tomorrow"], ["sa Lunes", "Monday"]], [["Puwede po ba {item}?", "Would {item} work?"], ["Hindi po puwede {item}.", "{item} will not work."], ["Okay lang po {item}.", "{item} is fine with me."], ["Kailangan po {item}.", "It has to be {item}."], ["Baka {item} po.", "Maybe {item}."]]) },
  { id: "market", icon: "◒", title: "At the palengke", intro: "Buy what you need, ask the price, and keep the exchange friendly.",
    phrases: phraseSet([["Magkano po ito?", "How much is this?"], ["Pahingi po ng kalahating kilo.", "May I have half a kilo, please?"], ["Puwede pong bawasan?", "Could you lower the price a little?"], ["Sariwa po ba ito?", "Is this fresh?"], ["May sukli po ba kayo?", "Do you have change?"], ["Pakisukat po ito.", "Please weigh this."], ["Ito na lang po.", "I’ll take this one instead."], ["Pakiabot po ng supot.", "Please pass me a bag."], ["Hindi na po, salamat.", "No more, thank you."], ["Babalik po ako mamaya.", "I’ll come back later."], ["Tingnan ko lang po.", "I’m just looking."], ["Magkano po lahat?", "How much is it altogether?"], ["Mahal naman po.", "That is a bit expensive."], ["May mas mura po ba?", "Is there a cheaper one?"], ["Wala po akong barya.", "I do not have small change."], ["Tig-magkano po?", "How much each?"], ["Sige po, kukunin ko na.", "All right, I’ll take it."], ["Pakibalot po nang maayos.", "Please wrap it up well."], ["Puwede po bang palitan ito?", "May I exchange this?"], ["Sa susunod na lang po.", "Maybe next time."]], [["kamatis", "tomatoes"], ["mangga", "mangoes"], ["isda", "fish"], ["itlog", "eggs"], ["manok", "chicken"], ["kanin", "rice"]], [["May {item} po ba?", "Do you have {item}?"], ["Magkano po ang {item}?", "How much are the {item}?"], ["Pahingi po ng {item}.", "May I have {item}, please?"], ["Puwede pong makita ang {item}?", "May I see the {item}?"], ["Pakidagdag po ang {item}.", "Please add the {item}."]]) },
  { id: "landlord", icon: "⌂", title: "With a landlord", intro: "Clear, polite lines for rent, repairs, and a first conversation.",
    phrases: phraseSet([["Magandang araw po. Interesado po ako sa unit.", "Good day. I’m interested in the unit."], ["Magkano po ang upa bawat buwan?", "How much is the rent each month?"], ["Kasama na po ba ang tubig at kuryente?", "Are water and electricity included?"], ["May sira po ang gripo sa banyo.", "The bathroom faucet is broken."], ["Kailan po puwedeng ayusin?", "When can it be fixed?"], ["Puwede ko po bang makita ang kontrata?", "May I see the contract?"], ["Kailan po ang bayad sa upa?", "When is rent due?"], ["May deposito po ba?", "Is there a deposit?"], ["Puwede po bang mag-alaga ng hayop?", "May I keep a pet?"], ["Pakisabi po kung may kailangan pa.", "Please tell me if anything else is needed."]], [["parking", "parking"], ["internet", "internet"], ["aircon", "air conditioning"], ["ref", "a refrigerator"], ["seguridad", "security"], ["tubig", "water"], ["kuryente", "electricity"], ["basurahan", "a trash bin"]], [["May {item} po ba sa unit?", "Is there {item} in the unit?"], ["Kasama na po ba ang {item}?", "Is {item} included?"], ["Puwede po bang gamitin ang {item}?", "May I use the {item}?"], ["May problema po sa {item}.", "There is a problem with the {item}."], ["Puwede po bang tingnan ang {item}?", "Could you check the {item}?"]]) },
  { id: "jeepney", icon: "▰", title: "In a jeepney", intro: "Navigate the ride with the phrases riders say every day.",
    phrases: phraseSet([["Bayad po.", "Fare, please."], ["Isa po, papuntang Cubao.", "One fare, to Cubao."], ["Para po!", "Please stop!"], ["Makikiraan po.", "Excuse me, I’m getting through."], ["Sukli po.", "My change, please."], ["Pakiabot po ng bayad.", "Please pass the fare."], ["Dito na lang po.", "Here is fine."], ["May bababa po.", "Someone is getting off."], ["Kasya pa po ba?", "Is there still room?"], ["Pakiusog po nang kaunti.", "Please move over a little."], ["Sa tabi lang po.", "By the side, please."], ["Magkano po ang pamasahe hanggang doon?", "How much is the fare going there?"], ["Estudyante po.", "Student fare, please."], ["Senior po siya.", "He or she is a senior citizen."], ["Puno na po ba?", "Is it full already?"], ["Sa unahan na lang po ako.", "I will sit up front instead."], ["Dalawa po kami.", "There are two of us."], ["Wala pa po akong sukli.", "I have not gotten my change yet."], ["Matrapik po ba sa daan?", "Is there traffic on the way?"], ["Huling biyahe na po ba ito?", "Is this the last trip?"]], [["Cubao", "Cubao"], ["Quiapo", "Quiapo"], ["Makati", "Makati"], ["terminal", "the terminal"], ["palengke", "the market"], ["istasyon", "the station"]], [["Papunta po ba sa {item}?", "Does this go to {item}?"], ["Dadaan po ba sa {item}?", "Does this pass through {item}?"], ["Saan po ang babaan sa {item}?", "Where do I get off for {item}?"], ["Sabihan n’yo po ako pag nasa {item} na.", "Please tell me when we are at {item}."], ["Malayo pa po ba ang {item}?", "Is {item} still far?"]]) },
  { id: "family", icon: "♡", title: "At a family gathering", intro: "Warm introductions and respectful language for meeting relatives.",
    phrases: phraseSet([["Magandang hapon po.", "Good afternoon."], ["Ako po si Sam. Ikinagagalak ko po kayo makilala.", "I’m Sam. It’s nice to meet you."], ["Ang sarap po ng pagkain.", "The food is delicious."], ["Kumain na po ba kayo?", "Have you eaten?"], ["Salamat po sa pag-imbita.", "Thank you for inviting me."], ["Tulungan ko po kayo.", "Let me help you."], ["Saan po ako uupo?", "Where should I sit?"], ["Kukuha lang po ako ng tubig.", "I’ll just get some water."], ["Ang saya po rito.", "It’s so nice here."], ["Ingat po sa pag-uwi.", "Take care going home."], ["Tuloy po kayo.", "Please come in."], ["Kain po tayo.", "Come and eat with us."], ["Busog na po ako, salamat.", "I am full already, thank you."], ["Konti lang po, salamat.", "Just a little, thank you."], ["Nakikiramay po ako.", "My condolences."], ["Maligayang bati po!", "Congratulations!"], ["Pasensya na po sa abala.", "Sorry for the trouble."], ["Ang bait naman po ninyo.", "That is so kind of you."], ["Kumusta po ang pamilya ninyo?", "How is your family?"], ["Uuwi na po kami, salamat sa lahat.", "We will head home now; thank you for everything."]], [["lola", "Grandma"], ["lolo", "Grandpa"], ["Tita", "Auntie"], ["Tito", "Uncle"], ["pinsan", "a cousin"], ["anak", "the child"]], [["Nasaan po si {item}?", "Where is {item}?"], ["Puwede ko po bang batiin si {item}?", "May I greet {item}?"], ["Kumusta na po si {item}?", "How is {item}?"], ["Puwede ko po bang makita si {item}?", "May I see {item}?"], ["Salamat po kay {item}.", "Thank {item} for me."]]) },
  { id: "bank", icon: "▤", title: "At the bank", intro: "Ask for help, explain a simple need, and confirm the next step.",
    phrases: phraseSet([["Magandang umaga po. May itatanong lang po ako.", "Good morning. I just have a question."], ["Gusto ko pong magbukas ng account.", "I would like to open an account."], ["Ano pong mga kailangan kong dalhin?", "What do I need to bring?"], ["Saan po ako pipila?", "Where should I line up?"], ["Salamat po sa tulong ninyo.", "Thank you for your help."], ["May appointment po ako.", "I have an appointment."], ["Puwede po ba akong kumuha ng numero?", "May I get a number?"], ["Pakiulit po, hindi ko narinig.", "Please repeat that; I did not hear."], ["Gaano po katagal ang proseso?", "How long does the process take?"], ["May bayad po ba?", "Is there a fee?"]], [["withdrawal", "a withdrawal"], ["deposito", "a deposit"], ["transfer", "a transfer"], ["ATM card", "an ATM card"], ["resibo", "a receipt"], ["account number", "an account number"], ["passbook", "a passbook"], ["ID", "an ID"]], [["Kailangan ko pong gumawa ng {item}.", "I need to make {item}."], ["Saan po ang para sa {item}?", "Where is the counter for {item}?"], ["Puwede po ba ang {item} rito?", "Can I do {item} here?"], ["May kailangan po ba para sa {item}?", "What is needed for {item}?"], ["Paki-check po ang {item} ko.", "Please check my {item}."]]) },
  { id: "restaurant", icon: "◉", title: "At a restaurant", intro: "Order, ask about ingredients, and handle the bill with ease.",
    phrases: phraseSet([["Mesa para sa dalawa, please.", "A table for two, please."], ["Puwede po bang makita ang menu?", "May I see the menu?"], ["Oorder na po kami.", "We are ready to order."], ["Ano po ang mairerekomenda ninyo?", "What do you recommend?"], ["Wala po akong allergy.", "I do not have any allergies."], ["Puwede pong hindi maanghang?", "Could it be not spicy?"], ["Paki-pack na lang po.", "Please pack it to go."], ["Pakiabot po ang tubig.", "Please pass the water."], ["Paki-check po ang bill.", "The bill, please."], ["Masarap po ang pagkain.", "The food is delicious."], ["Hindi po ako kumakain ng baboy.", "I do not eat pork."], ["Vegetarian po ako.", "I am vegetarian."], ["Walang bawang po, kung puwede.", "No garlic, if possible."], ["Tubig na walang yelo po.", "Water with no ice, please."], ["Puwede po bang magdagdag ng kanin?", "Could I have extra rice?"], ["Paki-hiwalay po ang bill namin.", "Please split our bill."], ["Take out po ito.", "This is to go."], ["Saan po ang CR?", "Where is the restroom?"], ["Hindi ko po ito inorder.", "I did not order this."], ["Puwede po bang mag-card?", "May I pay by card?"]], [["adobo", "adobo"], ["sinigang", "sinigang"], ["pancit", "pancit"], ["kanin", "rice"], ["tubig", "water"], ["kape", "coffee"]], [["May {item} po ba?", "Do you have {item}?"], ["Pahingi po ng {item}.", "May I have {item}, please?"], ["Magkano po ang {item}?", "How much is the {item}?"], ["Puwede pong dagdagan ng {item}?", "Could you add {item}?"], ["Paki-pack po ang {item}.", "Please pack the {item} to go."]]) },
  { id: "clinic", icon: "✚", title: "At a clinic or pharmacy", intro: "Explain a basic symptom, ask for medicine, and understand the next step.",
    phrases: phraseSet([["Masama po ang pakiramdam ko.", "I do not feel well."], ["Masakit po ang ulo ko.", "My head hurts."], ["May lagnat po ako.", "I have a fever."], ["May allergy po ako sa gamot na ito.", "I am allergic to this medicine."], ["Kailangan ko po ng doktor.", "I need a doctor."], ["May appointment po ako.", "I have an appointment."], ["Kailan po ako tatawagin?", "When will I be called?"], ["Pakiusap, dahan-dahan lang po.", "Please, slowly."], ["Paano po ito inumin?", "How do I take this?"], ["Kailangan ko po ng reseta.", "I need a prescription."], ["Ilang beses po sa isang araw?", "How many times a day?"], ["Bago o pagkatapos po kumain?", "Before or after eating?"], ["Ilang araw ko po iinumin?", "How many days do I take it?"], ["May side effect po ba ito?", "Does this have side effects?"], ["May allergy po ako sa penicillin.", "I am allergic to penicillin."], ["Buntis po ako.", "I am pregnant."], ["May alta-presyon po ako.", "I have high blood pressure."], ["May diabetes po ako.", "I have diabetes."], ["May hika po ako.", "I have asthma."], ["Nahihilo po ako.", "I feel dizzy."], ["Nagsusuka po ako.", "I have been vomiting."], ["Masakit po ang tiyan ko.", "My stomach hurts."], ["Hirap po akong huminga.", "I am having trouble breathing."], ["Tatlong araw na po itong masakit.", "It has been hurting for three days."], ["May insurance po ako.", "I have insurance."]], [["gamot sa ubo", "cough medicine"], ["gamot sa sipon", "cold medicine"], ["pain reliever", "a pain reliever"], ["thermometer", "a thermometer"], ["vitamins", "vitamins"]], [["May {item} po ba?", "Do you have {item}?"], ["Kailangan ko po ng {item}.", "I need {item}."], ["Magkano po ang {item}?", "How much is the {item}?"], ["Paano po gamitin ang {item}?", "How do I use {item}?"], ["Puwede po bang bumili ng {item} rito?", "Can I buy {item} here?"]]) },
  { id: "ride", icon: "↗", title: "In a taxi or ride-hail", intro: "Confirm the trip, give a clear destination, and travel more comfortably.",
    phrases: phraseSet([["May booking po ako.", "I have a booking."], ["Ako po si Sam.", "I’m Sam."], ["Papunta po ako sa address na ito.", "I’m going to this address."], ["Dito na lang po ako bababa.", "I’ll get off here."], ["Puwede pong dahan-dahan lang?", "Could you go slowly?"], ["Puwede po bang maghintay ng limang minuto?", "Could you wait five minutes?"], ["Mainit po ba sa loob?", "Is it warm inside?"], ["Puwede pong buksan ang aircon?", "Could you turn on the air conditioning?"], ["Magkano po ang pamasahe?", "How much is the fare?"], ["Salamat po, ingat po.", "Thank you, take care."]], [["hotel", "the hotel"], ["airport", "the airport"], ["istasyon", "the station"], ["opisina", "the office"], ["bahay", "home"], ["mall", "the mall"], ["klinika", "the clinic"], ["terminal", "the terminal"]], [["Papunta po ako sa {item}.", "I am going to {item}."], ["Alam n’yo po ba ang daan papuntang {item}?", "Do you know the way to {item}?"], ["Malapit na po ba ang {item}?", "Is {item} nearby?"], ["Puwede po bang dumaan sa {item}?", "Could we pass by {item}?"], ["Pakibaba po ako sa {item}.", "Please drop me off at {item}."]]) },
  { id: "directions", icon: "⌁", title: "Asking for directions", intro: "Find your way without needing to translate every word in your head.",
    phrases: phraseSet([["Saan po ang banyo?", "Where is the bathroom?"], ["Naliligaw po ako.", "I am lost."], ["Puwede po bang magtanong?", "May I ask a question?"], ["Paano po pumunta roon?", "How do I get there?"], ["Malapit lang po ba?", "Is it nearby?"], ["Lalakad lang po ba ako?", "Should I just walk?"], ["Kaliwa o kanan po?", "Left or right?"], ["May landmark po ba?", "Is there a landmark?"], ["Salamat po sa direksiyon.", "Thank you for the directions."], ["Naiintindihan ko na po.", "I understand now."]], [["bangko", "the bank"], ["palengke", "the market"], ["istasyon", "the station"], ["mall", "the mall"], ["paaralan", "the school"], ["ospital", "the hospital"], ["terminal", "the terminal"], ["hotel", "the hotel"]], [["Saan po ang {item}?", "Where is {item}?"], ["Paano po pumunta sa {item}?", "How do I get to {item}?"], ["Malayo po ba ang {item}?", "Is {item} far?"], ["Dadaan po ba ako sa {item}?", "Will I pass by {item}?"], ["Ito na po ba ang daan papuntang {item}?", "Is this the way to {item}?"]]) },
  { id: "work", icon: "□", title: "At work or school", intro: "Introduce yourself, ask for help, and keep everyday tasks moving.",
    phrases: phraseSet([["Magandang umaga po.", "Good morning."], ["Bago po ako rito.", "I am new here."], ["Puwede po bang magtanong?", "May I ask a question?"], ["Pakiulit po nang dahan-dahan.", "Please repeat it slowly."], ["Hindi ko pa po naiintindihan.", "I do not understand yet."], ["Puwede po ba akong tumulong?", "May I help?"], ["Natapos ko na po.", "I have finished."], ["Kailan po ang deadline?", "When is the deadline?"], ["May meeting po ba mamaya?", "Is there a meeting later?"], ["Salamat po sa paliwanag.", "Thank you for the explanation."], ["Male-late po ako nang kaunti.", "I will be a little late."], ["Nasa trapiko po ako ngayon.", "I am stuck in traffic right now."], ["Hindi po ako makakapasok, may sakit po ako.", "I cannot come in; I am sick."], ["Puwede po bang mag-leave bukas?", "May I take leave tomorrow?"], ["Kailangan ko pong umalis nang maaga.", "I need to leave early."], ["Tinatapos ko na po.", "I am finishing it now."], ["Puwede po bang ipaliwanag ulit?", "Could you explain it once more?"], ["Sino po ang dapat kong kausapin?", "Whom should I speak with?"], ["Ipapasa ko po mamaya.", "I will submit it later."], ["Pasensya na po sa pagkaantala.", "Sorry for the delay."]], [["meeting", "the meeting"], ["assignment", "the assignment"], ["report", "the report"], ["email", "the email"], ["computer", "the computer"], ["schedule", "the schedule"]], [["Saan po ang {item}?", "Where is {item}?"], ["Kailangan ko po ng {item}.", "I need {item}."], ["Puwede po bang gamitin ang {item}?", "May I use {item}?"], ["Paki-check po ang {item} ko.", "Please check my {item}."], ["May problema po sa {item}.", "There is a problem with the {item}."]]) }
];

phrasebookScenarios.push(
  { id: "everyday", icon: "*", title: "Everyday conversation", intro: "The small talk, invitations, and natural replies that turn a visit into a life here.",
    phrases: phraseSet([["Kumusta?", "How are you?"], ["Ayos lang naman.", "I'm okay."], ["Ano'ng balita?", "What's new?"], ["Saan ka galing?", "Where have you come from?"], ["Saan ka pupunta?", "Where are you going?"], ["Tara, kain tayo.", "Come on, let's eat."], ["Sige, tara.", "Sure, let's go."], ["Sandali lang.", "Just a moment."], ["Mamaya na lang.", "Maybe later."], ["Text mo na lang ako.", "Just text me."], ["May asawa ka na ba?", "Are you married?"], ["Wala pa.", "Not yet."], ["May asawa na ako.", "I am married."], ["Ilang taon ka na?", "How old are you?"], ["Bakit ka napunta sa Pilipinas?", "What brought you to the Philippines?"], ["Trabaho ang dahilan ko.", "I am here for work."], ["Dalawang taon na ako rito.", "I have been here two years."], ["Baka hindi ako makakapunta.", "I might not be able to come."], ["Hindi ako sigurado sa schedule ko.", "I am not sure about my schedule."], ["Salamat sa pag-aya, pero hindi ako makakasama.", "Thanks for the invitation, but I cannot join."]], [["kape", "coffee"], ["tanghalian", "lunch"], ["hapunan", "dinner"], ["weekend", "the weekend"], ["sine", "a movie"], ["mga kaibigan", "some friends"]], [["Tara, {item} tayo.", "Let's have/go to {item}."], ["Gusto mo ng {item}?", "Would you like {item}?"], ["May plano ka ba sa {item}?", "Do you have plans for {item}?"], ["Kita tayo sa {item}.", "Let's meet at {item}."], ["Sama ka sa {item}.", "Come along to {item}."]]) },
  { id: "home", icon: "H", title: "At home and in the neighborhood", intro: "Handle day-to-day home life, neighbors, visitors, and the little things that need sorting out.",
    phrases: phraseSet([["May tao po ba?", "Is anyone home?"], ["Ako po ito, kapitbahay ninyo.", "It's me, your neighbor."], ["Pakibuksan na lang po ang gate.", "Please open the gate."], ["Pakiwan na lang po sa guard.", "Please leave it with the guard."], ["May bisita po ako.", "I have a visitor."], ["Pakiusap, hinaan n'yo po ang boses.", "Please lower your voices."], ["Pasensya na po sa ingay.", "Sorry for the noise."], ["May nawawala po bang susi?", "Is anyone missing keys?"], ["Puwede po bang makahiram?", "May I borrow it?"], ["Ibabalik ko rin agad.", "I'll return it right away."]], [["walis", "a broom"], ["timba", "a bucket"], ["susi", "a key"], ["extension cord", "an extension cord"], ["payong", "an umbrella"], ["hagdan", "a ladder"], ["vacuum", "a vacuum"], ["panglinis", "cleaning supplies"]], [["May {item} ba kayo?", "Do you have {item}?"], ["Puwede bang makahiram ng {item}?", "May I borrow {item}?"], ["Saan ko puwedeng ilagay ang {item}?", "Where can I put {item}?"], ["Nakita n'yo ba ang {item}?", "Have you seen {item}?"], ["Pakiabot nga ang {item}.", "Please pass the {item}."]]) },
  { id: "delivery", icon: "D", title: "Deliveries and online shopping", intro: "Receive parcels, coordinate riders, and solve the usual delivery mix-ups.",
    phrases: phraseSet([["May inaasahan po akong delivery.", "I'm expecting a delivery."], ["Nasa bahay na po ako.", "I'm home now."], ["Nasa lobby po ako.", "I'm in the lobby."], ["Paki-message na lang po ako pag nandito na kayo.", "Please message me when you are here."], ["Pakiwan na lang po sa guard.", "Please leave it with the guard."], ["Ito po ang landmark.", "This is the landmark."], ["Maling item po ang dumating.", "The wrong item arrived."], ["May kulang po sa order ko.", "Something is missing from my order."], ["Sira po ang natanggap ko.", "What I received is damaged."], ["Puwede po bang i-return o i-refund?", "May I return it or get a refund?"]], [["order number", "my order number"], ["tracking number", "the tracking number"], ["address", "the address"], ["landmark", "the landmark"], ["COD", "cash on delivery"], ["resibo", "the receipt"], ["package", "the package"], ["rider", "the rider"]], [["Ito po ang {item} ko.", "Here is my {item}."], ["Paki-check po ang {item}.", "Please check the {item}."], ["May problema po sa {item}.", "There is a problem with the {item}."], ["Nasaan na po ang {item}?", "Where is the {item} now?"], ["Puwede po bang i-update ang {item}?", "Can the {item} be updated?"]]) },
  { id: "utilities", icon: "U", title: "Utilities and internet", intro: "Report an outage, arrange a visit, and ask the questions that keep a household connected.",
    phrases: phraseSet([["Wala pong kuryente sa amin.", "We have no electricity."], ["Mahina po ang tubig.", "The water pressure is weak."], ["Walang tubig mula kaninang umaga.", "There has been no water since this morning."], ["Wala pong internet.", "There is no internet."], ["Mabagal po ang koneksiyon.", "The connection is slow."], ["Kumukurap po ang ilaw.", "The light is flickering."], ["May tagas po ang tubo.", "The pipe is leaking."], ["Kailan po babalik ang serbisyo?", "When will the service return?"], ["Puwede po bang magpadala ng technician?", "Could you send a technician?"], ["May reference number po ako.", "I have a reference number."]], [["bill", "the bill"], ["metro", "the meter"], ["router", "the router"], ["modem", "the modem"], ["account number", "the account number"], ["reference number", "the reference number"], ["linya", "the line"], ["appointment", "the appointment"]], [["Paki-check po ang {item} namin.", "Please check our {item}."], ["May problema po sa {item}.", "There is a problem with the {item}."], ["Kailan po ang {item}?", "When is the {item}?"], ["Puwede po bang i-update ang {item}?", "Can the {item} be updated?"], ["Ito po ang {item} ko.", "Here is my {item}."]]) },
  { id: "government", icon: "G", title: "Government and paperwork", intro: "Navigate forms, IDs, copies, appointments, and the patient follow-up they often require.",
    phrases: phraseSet([["May appointment po ako.", "I have an appointment."], ["Ano pong requirements ang kailangan?", "What requirements are needed?"], ["Saan po ako kukuha ng form?", "Where can I get a form?"], ["Puwede po bang magpa-photocopy rito?", "Can I make photocopies here?"], ["Kailangan po ba ng original?", "Is the original required?"], ["May kopya po ako nito.", "I have a copy of this."], ["Puwede po bang magbayad online?", "Can I pay online?"], ["Kailan po ang release nito?", "When will this be released?"], ["Paano ko po masusundan ang application ko?", "How can I follow up on my application?"], ["May kulang pa po ba sa papeles ko?", "Are any of my documents still missing?"]], [["passport", "my passport"], ["visa", "my visa"], ["barangay clearance", "a barangay clearance"], ["birth certificate", "a birth certificate"], ["ID", "an ID"], ["application", "my application"], ["resibo", "the receipt"], ["reference number", "the reference number"]], [["Kailangan po ba ng {item}?", "Is {item} required?"], ["Saan po isusumite ang {item}?", "Where do I submit the {item}?"], ["Puwede po bang i-check ang {item} ko?", "Could you check my {item}?"], ["May kopya po ako ng {item}.", "I have a copy of {item}."], ["Kailan po makukuha ang {item}?", "When can I get the {item}?"]]) },
  { id: "emergency", icon: "!", title: "Emergencies and safety", intro: "Say what is happening clearly, get help, and protect yourself in an urgent moment.",
    phrases: phraseSet([["Tulong po!", "Help!"], ["Tumawag po kayo ng ambulansiya.", "Please call an ambulance."], ["Tumawag po kayo ng pulis.", "Please call the police."], ["May emergency po.", "There is an emergency."], ["Nasaan ang pinakamalapit na ospital?", "Where is the nearest hospital?"], ["Nawawala po ang wallet ko.", "My wallet is missing."], ["Nanakaw po ang phone ko.", "My phone was stolen."], ["Hindi ko kilala ang taong ito.", "I do not know this person."], ["Hindi po ako ligtas dito.", "I do not feel safe here."], ["Pakiusap, samahan n'yo po ako.", "Please come with me."], ["Sunog! Nasusunog po!", "Fire! Something is burning!"], ["May naaksidente po.", "Someone has been in an accident."], ["Hindi po siya humihinga.", "He or she is not breathing."], ["Wala pong malay ang tao.", "The person is unconscious."], ["May duguan po rito.", "Someone here is bleeding."], ["Nawawala po ang anak ko.", "My child is missing."], ["Layuan mo ako!", "Get away from me!"], ["Huwag mo akong hawakan!", "Do not touch me!"], ["Tatawag po ako ng pulis.", "I am going to call the police."], ["Saan po ang pinakamalapit na police station?", "Where is the nearest police station?"], ["Kailangan ko pong tumawag sa embahada namin.", "I need to call our embassy."], ["Nadukot po ang pitaka ko.", "My wallet was pickpocketed."], ["Sinundan po ako ng isang tao.", "Someone followed me."], ["Puwede po bang magpahiram ng telepono?", "May I borrow a phone?"], ["Ito po ang numero ng emergency contact ko.", "This is my emergency contact number."]], [["ID", "my ID"], ["passport", "my passport"], ["phone", "my phone"], ["bag", "my bag"], ["susi", "my keys"]], [["Nawawala po ang {item} ko.", "My {item} is missing."], ["Kailangan ko pong hanapin ang {item} ko.", "I need to find my {item}."], ["May nakakita po ba ng {item}?", "Has anyone seen the {item}?"], ["Ito po ang impormasyon ng {item}.", "Here is the information for the {item}."], ["Pakiusap, tulungan n'yo akong hanapin ang {item}.", "Please help me find the {item}."]]) },
  { id: "weather", icon: "W", title: "Weather and disasters", intro: "Understand the everyday weather talk and communicate safely during rain, flooding, earthquakes, or storms.",
    phrases: phraseSet([["Umuulan na naman.", "It's raining again."], ["Ang init ngayon.", "It's hot today."], ["May bagyo raw.", "They say there is a typhoon."], ["Baha na ba sa inyo?", "Is it flooding where you are?"], ["Huwag muna tayong lumabas.", "Let's not go out yet."], ["Lumindol ba?", "Was that an earthquake?"], ["Ligtas ba kayo?", "Are you safe?"], ["May evacuation center ba malapit?", "Is there an evacuation center nearby?"], ["Mataas ang tubig sa kalsada.", "The water is high on the road."], ["Mag-ingat kayo sa biyahe.", "Take care on your trip."]], [["payong", "an umbrella"], ["kapote", "a raincoat"], ["flashlight", "a flashlight"], ["tubig", "water"], ["pagkain", "food"], ["power bank", "a power bank"], ["gamot", "medicine"], ["emergency kit", "an emergency kit"]], [["May {item} ba kayo?", "Do you have {item}?"], ["Dalhin mo ang {item}.", "Bring the {item}."], ["Nasaan ang {item}?", "Where is the {item}?"], ["Kailangan natin ng {item}.", "We need {item}."], ["Huwag kalimutan ang {item}.", "Don't forget the {item}."]]) },
  { id: "personalcare", icon: "P", title: "Personal care and errands", intro: "Book a haircut, pick up laundry, and communicate the routine details of looking after yourself.",
    phrases: phraseSet([["May appointment po ako.", "I have an appointment."], ["Puwede po bang magpa-haircut?", "Can I get a haircut?"], ["Konti lang po ang bawas.", "Just a little off, please."], ["Ganitong haba lang po.", "Just this length, please."], ["Puwede po bang magpa-singaw?", "Can I get a facial?"], ["May laundry po ako.", "I have laundry."], ["Kailan ko po puwedeng kunin?", "When can I pick it up?"], ["May mantsa po rito.", "There is a stain here."], ["Paki-singaw na lang po.", "Please steam it instead."], ["Cash o GCash po ba?", "Cash or GCash?"]], [["haircut", "a haircut"], ["manicure", "a manicure"], ["pedicure", "a pedicure"], ["laundry", "my laundry"], ["comforter", "a comforter"], ["damit", "my clothes"], ["resibo", "the receipt"], ["appointment", "the appointment"]], [["Magkano po ang {item}?", "How much is {item}?"], ["May {item} po ba kayo?", "Do you offer {item}?"], ["Kailan po ang {item}?", "When is the {item}?"], ["Paki-check po ang {item} ko.", "Please check my {item}."], ["Puwede po bang kunin ang {item} ko?", "May I pick up my {item}?"]]) },
  { id: "payments", icon: "$", title: "Mobile, GCash, and payments", intro: "Handle cashless payments, load, transfers, and the quick confirmations used every day.",
    phrases: phraseSet([["May GCash po ba kayo?", "Do you accept GCash?"], ["Puwede po bang mag-cashless?", "Can I pay cashless?"], ["Ise-send ko na lang po.", "I'll send it instead."], ["Paki-check po kung pumasok na.", "Please check whether it has come through."], ["Hindi pa po pumapasok.", "It hasn't come through yet."], ["Puwede po bang magpa-load?", "Can I buy mobile load?"], ["Anong number po ang papadalhan?", "What number should I send it to?"], ["May cash po ba kayo?", "Do you have cash?"], ["Kulang po ang sukli ko.", "My change is short."], ["Paki-send po ang resibo.", "Please send the receipt."]], [["QR code", "the QR code"], ["GCash number", "the GCash number"], ["amount", "the amount"], ["screenshot", "the screenshot"], ["reference number", "the reference number"], ["load", "mobile load"], ["transfer", "the transfer"], ["bayad", "the payment"]], [["Paki-send po ang {item}.", "Please send the {item}."], ["Paki-check po ang {item}.", "Please check the {item}."], ["Ito po ang {item} ko.", "Here is my {item}."], ["May problema po sa {item}.", "There is a problem with the {item}."], ["Nakuha n'yo na po ba ang {item}?", "Have you received the {item}?"]]) },
  { id: "pets", icon: "@", title: "Pets and caregiving", intro: "Arrange vet care, ask for help with a pet or child, and cover the basics of everyday caregiving.",
    phrases: phraseSet([["May alaga akong aso o pusa.", "I have a dog or cat."], ["Kailangan ko pong dalhin sa vet.", "I need to take them to the vet."], ["May schedule po ba kayo?", "Do you have an available schedule?"], ["Kumain na po ba siya?", "Has he/she eaten?"], ["Uminom na po ba siya ng gamot?", "Has he/she taken medicine?"], ["May allergy po siya.", "He/she has an allergy."], ["Paki-text na lang po ako kung may problema.", "Please text me if there is a problem."], ["Anong oras po siya natulog?", "What time did he/she sleep?"], ["Puwede po ba akong mag-iwan ng instructions?", "May I leave instructions?"], ["Salamat po sa pag-aalaga.", "Thank you for taking care of them."]], [["bakuna", "a vaccine"], ["gamot", "medicine"], ["pagkain", "food"], ["leash", "a leash"], ["carrier", "a carrier"], ["litter", "litter"], ["reseta", "a prescription"], ["appointment", "an appointment"]], [["Kailangan po ng {item}.", "They need {item}."], ["May {item} po ba kayo?", "Do you have {item}?"], ["Magkano po ang {item}?", "How much is {item}?"], ["Paano po gamitin ang {item}?", "How do I use {item}?"], ["Kailan po ang {item}?", "When is the {item}?"]]) },
  { id: "phone", icon: "T", title: "On the phone", intro: "Calls you did not plan for: riders, landlords, clinics, and the wrong number at seven in the morning.",
    phrases: phraseSet([["Hello po, sino po sila?", "Hello, who is this?"], ["Hello po, si Sam po ito.", "Hello, this is Sam."], ["Sandali lang po, huwag po ninyong ibaba.", "One moment, please do not hang up."], ["Mali po yata ang na-dial ninyo.", "I think you dialed the wrong number."], ["Wala po siya ngayon.", "He or she is not here right now."], ["Nasa labas po siya.", "He or she is out."], ["May ipapasabi po ba kayo?", "Would you like to leave a message?"], ["Pakiulit po ng pangalan ninyo.", "Please repeat your name."], ["Hindi ko po kayo marinig.", "I cannot hear you."], ["Mahina po ang signal ko.", "My signal is weak."], ["Nagpuputol-putol po ang tawag.", "The call keeps cutting out."], ["Puwede po bang tawagan ko na lang kayo ulit?", "May I call you back instead?"], ["Anong number po ang tatawagan ko?", "What number should I call?"], ["Nasa meeting po ako, mamaya na lang po.", "I am in a meeting; later, please."], ["Text na lang po kayo sa akin.", "Just text me instead."], ["Paki-message na lang po ako.", "Please just message me."], ["Hindi po ako makatawag, walang load.", "I cannot call; I have no load."], ["May missed call po kayo sa akin kanina.", "You had a missed call to me earlier."], ["Sino po ang kausap ko?", "Whom am I speaking with?"], ["Puwede po bang mag-iwan ng number ninyo?", "May I have your number?"], ["Nandito na po ako sa labas.", "I am outside now."], ["Papunta na po ako.", "I am on my way."], ["Salamat po sa pagtawag.", "Thank you for calling."], ["Sige po, ibababa ko na.", "All right, I will hang up now."], ["Tatawag po ako ulit mamaya.", "I will call again later."]], [["appointment", "the appointment"], ["address", "the address"], ["order", "the order"], ["schedule", "the schedule"], ["booking", "the booking"]], [["Tumatawag po ako tungkol sa {item}.", "I am calling about {item}."], ["Paki-check po ang {item}.", "Please check {item}."], ["Puwede po bang kumpirmahin ang {item}?", "Could you confirm {item}?"], ["Pakiulit po ang {item}.", "Please repeat {item}."], ["May pagbabago po sa {item}.", "There is a change to {item}."]]) }
);

function speak(text) {
  if (!("speechSynthesis" in window)) return;
  window.speechSynthesis.cancel();
  const utterance = new SpeechSynthesisUtterance(text);
  utterance.lang = "fil-PH";
  utterance.rate = 0.82;
  window.speechSynthesis.speak(utterance);
}

function wireAudio() {
  document.addEventListener("click", event => {
    const button = event.target.closest("[data-audio-target], [data-speak]");
    if (!button) return;
    const text = button.dataset.speak || document.querySelector(`#${button.dataset.audioTarget}`)?.textContent;
    if (text) speak(text);
  });
}

function renderAffixTree() {
  const rootTabs = document.querySelector("#rootTabs");
  if (!rootTabs) return;
  let selectedRoot = "kain";
  let selectedPath = 0;
  const render = () => {
    const root = affixRoots[selectedRoot];
    rootTabs.innerHTML = Object.entries(affixRoots).map(([id, data]) => `<button type="button" role="tab" aria-selected="${id === selectedRoot}" class="root-tab ${id === selectedRoot ? "active" : ""}" data-root="${id}"><strong>${data.label}</strong><span>${data.gloss}</span></button>`).join("");
    document.querySelector("#treeRoot").innerHTML = `<span>ROOT</span><strong>${root.label}</strong><small>${root.gloss}</small><p>${root.description}</p>`;
    document.querySelector("#treeBranches").innerHTML = root.paths.map((path, index) => `<button class="tree-branch ${index === selectedPath ? "active" : ""}" type="button" role="listitem" aria-pressed="${index === selectedPath}" data-path="${index}"><span class="branch-line" aria-hidden="true"></span><small>${path.focus} route</small><strong>${path.affix}</strong><em>${path.form}</em></button>`).join("");
    const path = root.paths[selectedPath];
    document.querySelector("#affixBadge").textContent = path.affix;
    document.querySelector("#affixForm").textContent = path.form;
    document.querySelector("#affixMeaning").textContent = path.meaning;
    document.querySelector("#affixFocus").textContent = path.focus;
    document.querySelector("#affixPattern").textContent = path.pattern;
    document.querySelector("#affixSentence").textContent = path.sentence;
    document.querySelector("#affixTranslation").textContent = path.translation;
  };
  rootTabs.addEventListener("click", event => { const button = event.target.closest("[data-root]"); if (!button) return; selectedRoot = button.dataset.root; selectedPath = 0; render(); });
  document.querySelector("#treeBranches").addEventListener("click", event => { const button = event.target.closest("[data-path]"); if (!button) return; selectedPath = Number(button.dataset.path); render(); });
  render();
}

function renderPairs() {
  const tabs = document.querySelector("#pairTabs");
  if (!tabs) return;
  let selected = 0;
  const render = () => {
    const pair = confusionPairs[selected];
    tabs.innerHTML = confusionPairs.map((item, index) => `<button class="pair-tab ${index === selected ? "active" : ""}" type="button" role="tab" aria-selected="${index === selected}" data-pair="${index}">${item.title}</button>`).join("");
    document.querySelector("#pairDetail").innerHTML = `<p class="section-number">The difference</p><h2>${pair.title}</h2><p class="pair-summary">${pair.summary}</p><div class="pair-rule"><strong>The shortcut</strong><p>${pair.rule}</p></div><div class="pair-examples">${pair.examples.map(([fil, en]) => `<article><p lang="fil">${fil}</p><span>${en}</span><button class="audio-button" type="button" data-speak="${fil}"><span aria-hidden="true">◖</span> Hear it</button></article>`).join("")}</div>`;
  };
  tabs.addEventListener("click", event => { const button = event.target.closest("[data-pair]"); if (!button) return; selected = Number(button.dataset.pair); render(); });
  render();
}

function renderPhrasebook() {
  const tabs = document.querySelector("#scenarioTabs");
  if (!tabs) return;
  let selected = 0;
  const search = document.querySelector("#phraseSearch");
  const render = () => {
    const scenario = phrasebookScenarios[selected];
    const query = search.value.trim().toLocaleLowerCase();
    const visiblePhrases = scenario.phrases.filter(([fil, en]) => `${fil} ${en}`.toLocaleLowerCase().includes(query));
    tabs.innerHTML = phrasebookScenarios.map((item, index) => `<button class="scenario-tab ${index === selected ? "active" : ""}" type="button" role="tab" aria-selected="${index === selected}" data-scenario="${index}"><span aria-hidden="true">${item.icon}</span>${item.title}</button>`).join("");
    document.querySelector("#scenarioLabel").textContent = `Situation ${selected + 1} of ${phrasebookScenarios.length} · ${scenario.phrases.length} phrases`;
    document.querySelector("#scenarioTitle").textContent = scenario.title;
    document.querySelector("#scenarioIntro").textContent = scenario.intro;
    document.querySelector("#phraseCount").textContent = query ? `${visiblePhrases.length} of ${scenario.phrases.length} phrases match “${search.value.trim()}”.` : `${scenario.phrases.length} phrases in this situation.`;
    document.querySelector("#phraseList").innerHTML = visiblePhrases.length
      ? visiblePhrases.map(([fil, en], index) => `<article class="phrase-card"><span class="phrase-number">${String(index + 1).padStart(2, "0")}</span><div><p lang="fil">${fil}</p><small>${en}</small></div></article>`).join("")
      : `<p class="empty-phrases">No matching phrase yet. Try a shorter word or another situation.</p>`;
  };
  tabs.addEventListener("click", event => { const button = event.target.closest("[data-scenario]"); if (!button) return; selected = Number(button.dataset.scenario); search.value = ""; render(); });
  search.addEventListener("input", render);
  render();
}

wireAudio();
renderAffixTree();
renderPairs();
renderPhrasebook();
